apiVersion: apps/v1
kind: Deployment
metadata:
  name: impv-a-receiver
  labels:
    {{- include "falcon-controller.labels" . | nindent 4 }}
spec:
  {{- if not .Values.receiver.autoscaling.enabled }}
  replicas: {{ .Values.receiver.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "falcon-controller.receiver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "falcon-controller.receiver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.receiver.podSecurityContext | nindent 8 }}
      volumes:
      - name: cert-volume-rcvr
        emptyDir: {}
      initContainers:  
      - name: cert-container
        image: img.cloudvector.net/localcert:generic
        command: ["cp",  "-R",  "/etc/certs/localbay",  "/cert"]
        volumeMounts:
        - mountPath: /cert
          name: cert-volume-rcvr
      containers:
        - name: receiver
          volumeMounts:
          - name: cert-volume-rcvr
            mountPath: /etc/certs/
          securityContext:
            {{ toYaml .Values.receiver.securityContext | nindent 12 }}
          image: "{{ .Values.receiver.image.repository }}:{{ .Values.receiver.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.receiver.image.pullPolicy }}
          {{- if .Values.receiver.env }}
          env:
          {{- range $k, $v := .Values.receiver.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
          {{- end }}
            - name: DEPLOYMENT_PROFILE
              valueFrom:
                secretKeyRef:
                  name: controller-secret
                  key: deployment-profile
            - name: CONTROLLER_ID
              valueFrom:
                secretKeyRef:
                  name: controller-secret
                  key: controller-id
            - name: CONTROLLER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: controller-secret
                  key:  controller-token
            - name: CONTROLLER_INSTANCE
              valueFrom:
                secretKeyRef:
                  name: controller-secret
                  key: controller-instance
            - name: ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: controller-secret
                  key: account-id
          {{- end }}
          resources:
            {{- toYaml .Values.receiver.resources | nindent 12 }}
      {{- with .Values.receiver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.receiver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.receiver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
