apiVersion: v1
kind: Secret
metadata:
  name: controller-secret
type: Opaque
data:
  controller-id: {{ .Values.CONTROLLER_ID | b64enc | quote }}
  account-id: {{ .Values.ACCOUNT_ID | b64enc | quote }}
  controller-token: {{ .Values.CONTROLLER_TOKEN | b64enc | quote }}
  controller-instance: {{ randAlphaNum 32 | b64enc | quote }}
  site-id: {{ .Values.SITE_ID | b64enc | quote }}
  deployment-profile: {{ .Values.DEPLOYMENT_PROFILE | b64enc | quote }}
