apiVersion: v1
kind: Service
metadata:
  name: cloud-connector
  labels:
    {{- include "falcon-controller.cloudConnector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cloudConnector.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "falcon-controller.cloudConnector.selectorLabels" . | nindent 4 }}
